# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sce_lik <- function(R, X, des, des_pos, des_n, prune, T, S) {
    .Call(`_sce_sce_lik`, R, X, des, des_pos, des_n, prune, T, S)
}

sce_rec <- function(R, bw_R, X, des, des_pos, des_n, prune, T, tip) {
    .Call(`_sce_sce_rec`, R, bw_R, X, des, des_pos, des_n, prune, T, tip)
}

